### ISSUE TITLE
In the background section update figure based on title

### ISSUE THREAD

**Issue by kjappelbaum** [lamalab-org/matextract-book#41]
> I think it is ready :)

thank you both very much!!
in the tiktokenizer I used the text of the actual title of the review, if we change it, and I don't forget, I will update this figure for the final version

_Originally posted by @vgvinter in https://github.com/lamalab-org/how-to-extract-structured-data-with-llms/issues/37#issuecomment-2183986400_

**Comment by MrtinoRG** [comment]
Can the title change again?

**Comment by kjappelbaum** [comment]
perhaps if the reviewers complain about it :)

**Comment by MrtinoRG** [comment]
Ok, that was my fear :)

**Comment by MrtinoRG** [comment]
So, we can close this @kjappelbaum?

**Comment by kjappelbaum** [comment]
yes, it is also in any case not a blocking thing :)
